### ISSUE TITLE
sqlite database is sometimes locked and error is not handled

### ISSUE THREAD

**Issue by jeanconn** [sot/timelines#23]
As far as I can tell, in this case, the job to update the sqlite table with new command loads from disk did not succeed due to lock.  But the job succeeded enough to update the "tracking" file so it is not trying to ingest the missing files.   

```
/proj/sot/ska/share/timelines//parse_cmd_load_gen.pl --dbi 'sqlite' --server /proj/sot/ska/data/cmd_states/cmd_st
ates.db3 --touch_file /proj/sot/ska/data/timelines/sum_files_sqlite3.touch  --verbose
############################################################
<<2019-Nov-26 09:20>> Updating clgps tables with files newer than /proj/sot/ska/data/timelines/sum_files_sqlite3.t
ouch
<<2019-Nov-26 09:20>> find -L /data/mpcrit1/mplogs//2018/[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]/ofls?/mps/  -maxdepth
 1 -wholename "*/ofls?/mps/C[0-9][0-9][0-9]?[0-9][0-9][0-9][0-9].sum"  -newer /proj/sot/ska/data/timelines/sum_fil
es_sqlite3.touch 
<<2019-Nov-26 09:20>> find -L /data/mpcrit1/mplogs//2019/[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]/ofls?/mps/  -maxdepth
 1 -wholename "*/ofls?/mps/C[0-9][0-9][0-9]?[0-9][0-9][0-9][0-9].sum"  -newer /proj/sot/ska/data/timelines/sum_fil
es_sqlite3.touch 
<<2019-Nov-26 09:20>> DBD::SQLite::db do failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUtil.pm 
line 154.
<<2019-Nov-26 09:21>> DBD::SQLite::st execute failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUti
l.pm line 144.
<<2019-Nov-26 09:21>> DBD::SQLite::db do failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUtil.pm 
line 154.
<<2019-Nov-26 09:22>> DBD::SQLite::st execute failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUti
l.pm line 144.
<<2019-Nov-26 09:22>> DBD::SQLite::db do failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUtil.pm 
line 154.
<<2019-Nov-26 09:23>> DBD::SQLite::st execute failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUti
l.pm line 144.
<<2019-Nov-26 09:23>> DBD::SQLite::db do failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUtil.pm 
line 154.
<<2019-Nov-26 09:24>> DBD::SQLite::st execute failed: database is locked at /proj/sot/ska/lib/perl/Ska/DatabaseUti
l.pm line 144.
<<2019-Nov-26 09:24>> Parsing /data/mpcrit1/mplogs//2019/DEC0219/oflsa/mps/C335_1801.sum ... Done

**Comment by taldcroft** [comment]
Yes, perl just infuriates me... I can see in the call to connect to the database that `raise_error => 1` is explicitly specified, so WHY does it not raise an error for the failed transaction??

One last resort is that this code `parse_cmd_load_gen.pl` is ignoring the return status of the `do` and `insert_hash` calls, so maybe those would give some hint of a problem and allow a croak.

**Comment by jeanconn** [comment]
Though it is still two issues; we don't quite understand sqlite locks on the Python side either.

**Comment by taldcroft** [comment]
Sure, but the sqlite locks issue is one for which we have never identified a solid resolution over the years.  The issue of not actually failing when a lock problem comes up is new and something that we might resolve in a few lines of code.

**Comment by jeanconn** [comment]
Agreed!  Which is why I opened this as a timelines issue and mean to fix it.  But I'm still annoyed that Sybase is doing a better job than Sqlite at this and that we've transitioned to the sometimes broken of the two.  It would be nice to either skip using a database for management of these data or to confirm that we are using a modern sqlite and current best practices.

**Comment by taldcroft** [comment]
The transition has come with some tremendous benefits so I don't regret the occasional hiccup.  We have known all along that sqlite + NFS = occasional problems.  I am not aware of any best practice in that regard except "don't do that".  So we deal with it.

Any sort of data persistence is not managed by a transactional DBM like Sybase is going to be subject to concurrency problems.  Having said that, getting away from sqlite where it is not bringing value-added is a fine thing.  But sqlite does provide some data integrity, selection and other features that can be useful.  HDF5 is not really ideal for data that change a lot.
